### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by sherryw1022** [fbattarra/wp-quiz-pro-exporter#2]
Hello, I couldn't import wp-pro-quiz-export.zip into my site but I could add via ftp and then enable where I could see the export option. It worked fine and I could see my quiz option. When I clicked on quiz - csv I got an internal error. I asked my hosting company and they said it had to do with the plugin. 
1. how can I fix this?
2. once I get the csv what is the easiest way to create metrics/stats?

thanks

**Comment by fbattarra** [comment]
Hi Sherryw1022, thank you for posting here your issue!

For the import-the-zip thing, can you please make sure your zip contains only what's into /build/wp-quiz-pro-exporter/ and not everything in this GITHub repository (as from the "Download ZIP" button on the repository home page) ?

About the error you obtain, can you please tell me something more? At the present moment the sub-plugin has been tested working only with WP-Pro-Quiz v0.37 on a WordPress 4.4.2 installation. Maybe also the PHP version (5.6 for the tested environment) can be the source.

The best thing you can do to help me is try to tell me more about the error you get, from the webserver logs and/or by setting an higher level of [error_reporting()](http://php.net/manual/en/function.error-reporting.php) somewhere in your WP (possibly using [some WP builtin debugging features](https://codex.wordpress.org/Debugging_in_WordPress)).

You'll then should be able to provide me some further, hopefully eye opening detail about what goes wrong.

Finally, I'm not an Excel guru, so I'd say once you retrieved all the possible data it's up to you to find how to draw conclusions (i.e. "the majority of participant failed at question #9 while succeeded at question #12 , and this can mean...")  :-)

Let me know

**Comment by sherryw1022** [comment]
Hi yes to zip question I clicked on build folder and uploaded the wp-pro-quiz-export folder .. I attempted to zip it and install but it wouldn't work. 
I get a 500 error internal server error when I click on csv to attempt to get quiz data.
My quiz plugin version is 0.37 and wordpress version 4.42.
I can grant you access to my site in a private message if that helps. 

in the console I see this on the error page which path is domain/wp-admin/admin-post.php 

The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

I will try and get more error info.
Thanks!

**Comment by fbattarra** [comment]
I'm kinda a newbie here on GITHub, can you already send me a pvt or should I write here my email? ;)

**Comment by sherryw1022** [comment]
I am brand new .. I am searching on how I can do this.

**Comment by sherryw1022** [comment]
let me know when I can remove credentials

**Comment by fbattarra** [comment]
as from StackOverflow it seems there's a tricky way to discover how to contact me (because private messaging has been removed) :D 

You can temporarily write me at [_removed_], then I'll change the password you'll give me and of course I'll write you when my access will be not anymore needed

**Comment by sherryw1022** [comment]
you can remove your email I sent it to you thx

**Comment by fbattarra** [comment]
removed. if the email address you used was valid, you got mail (and please delete the account you sent me ;-)

**Comment by sherryw1022** [comment]
hey there - any luck?

**Comment by fbattarra** [comment]
hey Sherry, didn't you receive the email I sent to your mailbox from my gmail account?
I indeed had no luck logging into your back-end with the account you provided me; in the meanwhile I sincerely hope you'll have deleted it in any case :)

Tell me if you haven't received my email, I'll manage to write you again (asking for another account ;-)

**Comment by sherryw1022** [comment]
Hi, I resend the email and I found an error in my user set up. You can try and login with what I posted yesterday :)

**Comment by fbattarra** [comment]
Sherry, you got mail. 

It's mainly because your server runs PHP 5.3 and I used a syntax supported only starting from PHP 5.4.

I'll manage to modify the code in order to remove this constraint.

**Comment by sherryw1022** [comment]
YOU ROCK! Thank You Very Much!

**Comment by fbattarra** [comment]
Here we are Sherry: I just pushed a new version of the file on the repository, now array declaration syntax does not require anymore PHP >= 5.4

I also updated your copy of the plugin and now it indeed works. You can delete my account @ your sandbox WP site.
