### ISSUE TITLE
Is it possible to support User Role Editor plugin ?

### ISSUE THREAD

**Issue by ausiuming** [fbattarra/wp-quiz-pro-exporter#3]
I have installed WP-Pro-Quiz and WP-Pro-Quiz Export. I also installed User Role Editor later and found that User Role Editor can editor functions in WP-Pro-Quiz but not the CSV export function. Is it possible to support the User Role Editor plugin ?

**Comment by fbattarra** [comment]
Hi ausiuming, and thank you for giving my sub-plugin a try :)

Being not that WP guru, I don't know (yet) the plugin you mentioned; at the present moment I cannot promise if nor when I'll have a look to maybe make the export function compatible with it. 

To tell you the truth, your best luck will be actually the client I developed the plugin for will ask for it (and it's not so improbable, as they may need to choose who has access to what, if I understood what the plugin should do). 

It's anyway interesting (and perhaps not that difficult to add), so ...stay tuned: I'll obviously reply to this thread whenever I'll add this compatibility :)

**Comment by olgalynch** [comment]
Hi ausiuming, did you solve this I am having the same issue.
