### ISSUE TITLE
Problem with CSV export

### ISSUE THREAD

**Issue by Camilmesfioui** [fbattarra/wp-quiz-pro-exporter#4]
Hi ! 

I have an issue with my CSV export. When i got to Statistics => Export CSV  i'm getting my CSV file as planned but when i open it the content in it was not what i expected ( Yes it is but i have a lot of stuff i didn't want ).

Thank you for your help ! :)

Here's a screenshot : 

https://s31.postimg.org/6npehohyz/Capture_d_e_cran_2016_07_06_a_13_55_47.png

**Comment by fbattarra** [comment]
Hi  Camilmesfioui,

It's just Microsoft Excel not really keen to properly open CSV files.
This is what I found among the firsts results googling how to split a CSV into columns with Excel:

[http://superuser.com/questions/407082/easiest-way-to-open-csv-with-commas-in-excel](http://superuser.com/questions/407082/easiest-way-to-open-csv-with-commas-in-excel)

Thank you for giving my sub-plugin a try!

**Comment by Camilmesfioui** [comment]
Thanks for your help ! :)
